"""Approval-code delivery + pending-escalation tracking — custom code via Twilio SMS.

Generates a 6-digit code server-side, sends it via Twilio SMS (not Verify), and
stores the code in state/pending_code.json with a TTL. This allows the operator
panel to display the code so judges can see it on screen without needing to look
at the operator's phone.

The security property that matters: the code is generated by this process and
sent out-of-band to the operator's real phone. The AI agent cannot read the state
directory or call approve.py directly — the kernel's Landlock sandbox prevents it.
"""
import json
import os
import random
import secrets
import sys
import time
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, "/sandbox/.hermes/lib/python-packages")
os.environ.setdefault("SSL_CERT_FILE", "/etc/openshell-tls/ca-bundle.pem")
os.environ.setdefault("REQUESTS_CA_BUNDLE", "/etc/openshell-tls/ca-bundle.pem")

import requests  # noqa: E402

SECRET_FILE = Path("/sandbox/.hermes/secrets/twilio.env")
PENDING_FILE = SKILL_DIR / "state" / "pending_approval.json"
PENDING_CODE_FILE = SKILL_DIR / "state" / "pending_code.json"
CODE_TTL = 600


class PendingEscalationExistsError(Exception):
    """Raised by write_pending() when an unexpired escalation is already
    on file. PENDING_FILE and PENDING_CODE_FILE are a single shared path
    per sandbox, not scoped per visitor/session — on a public demo with
    concurrent traffic, a second write_pending() call would otherwise
    silently overwrite the first escalation's record and code. Whoever
    is holding the first SMS code would then have it stop matching
    anything, or a stray unlink from the second flow could delete the
    file entirely — surfacing to them as approve.py's plain "No pending
    escalation found", with no indication a second request came in.
    Refusing to clobber turns that into an honest, immediate error at
    the point the second request is made instead."""


def _atomic_write(path: Path, content: str) -> None:
    """Atomic write: temp file + rename on same fs. Matters here for the
    same reason write_pending() now refuses to clobber a live pending
    escalation — a torn/partial write from a non-atomic write_text(),
    raced by a concurrent read from approve.py, could itself surface as
    a phantom 'no pending escalation' or a corrupt-JSON read.

    fsync's fd must come from the SAME file object the whole way through
    (via a `with` block) — a previous version called
    `os.fsync(tmp_path.open("rb").fileno())`, whose anonymous file object
    has no reference held once .fileno() returns, so CPython's refcounting
    GC could close it immediately and hand fsync an already-closed fd
    (reproducible: OSError: [Errno 9] Bad file descriptor)."""
    dir_path = path.parent
    dir_path.mkdir(parents=True, exist_ok=True)
    tmp_name = str(path) + f".tmp.{os.getpid()}.{random.randint(100000, 999999)}"
    tmp_path = Path(tmp_name)
    try:
        with open(tmp_path, "w") as f:
            f.write(content)
            f.flush()
            os.fsync(f.fileno())
        # os.replace, not os.rename: POSIX rename(2) silently replaces an
        # existing target, but on Windows os.rename raises FileExistsError
        # (WinError 183) -- so rewriting a pending-escalation file that already
        # existed failed there while passing on Linux. os.replace is the
        # portable form and is atomic on both.
        os.replace(str(tmp_path), str(path))
    except Exception:
        try:
            tmp_path.unlink(missing_ok=True)
        except OSError:
            pass
        raise


def _load_secrets():
    vals = {}
    for line in SECRET_FILE.read_text().splitlines():
        if "=" in line:
            k, v = line.split("=", 1)
            vals[k.strip()] = v.strip()
    return vals


def _existing_pending_is_live() -> bool:
    if not PENDING_FILE.exists():
        return False
    try:
        record = json.loads(PENDING_FILE.read_text())
    except (json.JSONDecodeError, OSError):
        return False  # unreadable/corrupt — treat as not blocking, not as live
    return time.time() - record.get("created_at", 0) <= CODE_TTL


def write_pending(amount, description, reason, kind="spend", payment_intent_id=None):
    if _existing_pending_is_live():
        raise PendingEscalationExistsError(
            "an escalation is already pending and unexpired — resolve it with "
            "approve.py (or wait for it to expire) before requesting another"
        )
    _atomic_write(PENDING_FILE, json.dumps({
        "amount": amount, "description": description, "reason": reason,
        "created_at": time.time(), "kind": kind, "payment_intent_id": payment_intent_id,
    }, indent=2))


def send_approval_code(amount: float, description: str) -> bool:
    secrets_map = _load_secrets()
    sid = secrets_map["TWILIO_ACCOUNT_SID"]
    token = secrets_map["TWILIO_AUTH_TOKEN"]
    from_number = secrets_map["TWILIO_FROM_NUMBER"]
    # Loaded from the same git-ignored secrets file as the Twilio credentials
    # above -- never a source-code default. A real phone number was
    # previously hardcoded here as a fallback default and got deployed to
    # the live sandbox outside of git; moving it into the secrets file is
    # what keeps it out of anything that gets committed or distributed.
    operator_phone = secrets_map["HERMES_OPERATOR_PHONE"]

    code = f"{secrets.randbelow(1000000):06d}"

    _atomic_write(PENDING_CODE_FILE, json.dumps({
        "code": code,
        "expires_at": time.time() + CODE_TTL,
    }))

    body = (
        f"Custodian approval code: {code}\n"
        f"${amount:.2f} — {description[:60]}\n"
        f"Expires in 10 min. Enter this in the operator panel."
    )
    r = requests.post(
        f"https://api.twilio.com/2010-04-01/Accounts/{sid}/Messages.json",
        auth=(sid, token),
        data={"To": operator_phone, "From": from_number, "Body": body},
        timeout=10,
    )
    r.raise_for_status()
    print(f"[notify:TWILIO SMS] Real approval code sent to operator phone "          f"for ${amount:.2f} spend ('{description}'). SID: {r.json().get('sid')}.")
    return True


def check_approval_code(code: str) -> bool:
    if not PENDING_CODE_FILE.exists():
        return False
    try:
        data = json.loads(PENDING_CODE_FILE.read_text())
    except (json.JSONDecodeError, OSError):
        return False
    if time.time() > data.get("expires_at", 0):
        PENDING_CODE_FILE.unlink(missing_ok=True)
        return False
    stored = str(data.get("code", "")).strip()
    entered = str(code).strip()
    if stored == entered:
        PENDING_CODE_FILE.unlink(missing_ok=True)
        return True
    return False
