#!/usr/bin/env bash
# MiniFW one-shot setup — run from the USB stick on the Mac Mini.
#   cd /media/$USER/MINIFWSETUP   (path varies)
#   sudo ./setup.sh
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root: sudo $0"
  exit 1
fi

USB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ ! -f "${USB_DIR}/.minifw-usb" ]]; then
  echo "Warning: this does not look like a MiniFW setup USB (.minifw-usb missing)."
  read -r -p "Continue anyway? [y/N] " ans
  [[ "${ans,,}" == "y" ]] || exit 1
fi

echo "╔══════════════════════════════════════════════════════════╗"
echo "║  MiniFW setup USB — Google Fiber + Mac Mini + Deco XE75  ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo
echo "USB path: ${USB_DIR}"
echo

# ── 1. Packages ──────────────────────────────────────────────────────────────
echo "==> [1/7] Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y nftables dnsmasq python3 python3-pip iproute2 curl

# ── 2. MiniFW ────────────────────────────────────────────────────────────────
echo "==> [2/7] Installing minifw from USB"
python3 -m pip install --break-system-packages "${USB_DIR}/minifw" -q

# ── 3. Offline docs on the Mac Mini (survives USB removal) ─────────────────
echo "==> [3/7] Installing offline docs to /opt/minifw"
install -d /opt/minifw/docs /opt/minifw/obsidian
cp -f "${USB_DIR}/docs/"*.md /opt/minifw/docs/ 2>/dev/null || true
cp -Rf "${USB_DIR}/obsidian/." /opt/minifw/obsidian/ 2>/dev/null || true
cp -f "${USB_DIR}/EMERGENCY-CARD.txt" /root/INTERNET-DOWN.txt
cp -f "${USB_DIR}/EMERGENCY-CARD.txt" /opt/minifw/EMERGENCY-CARD.txt
chmod 644 /opt/minifw/docs/* /root/INTERNET-DOWN.txt 2>/dev/null || true

# ── 4. Detect interfaces ─────────────────────────────────────────────────────
echo "==> [4/7] Detecting network interfaces"
echo
ip -br link
echo

WAN_IF=""
LAN_IF=""

# USB adapters: enx* or name contains usb
while IFS= read -r line; do
  name="${line%% *}"
  [[ "${name}" == "lo" ]] && continue
  [[ "${name}" == enx* ]] && WAN_IF="${name}" && continue
  [[ "${name}" == *usb* ]] && WAN_IF="${name}" && continue
done < <(ip -br link | awk '{print $1}')

# Built-in: first non-lo, non-wan, non-docker
while IFS= read -r line; do
  name="${line%% *}"
  [[ "${name}" == "lo" ]] && continue
  [[ "${name}" == "${WAN_IF}" ]] && continue
  [[ "${name}" == docker* ]] && continue
  [[ "${name}" == veth* ]] && continue
  [[ "${name}" == br-* ]] && continue
  LAN_IF="${name}"
  break
done < <(ip -br link | awk '{print $1}')

if [[ -z "${WAN_IF}" ]]; then
  echo "USB WAN adapter not detected. Plug in the USB Ethernet adapter and re-run."
  echo "Available interfaces:"
  ip -br link
  exit 1
fi

if [[ -z "${LAN_IF}" ]]; then
  echo "LAN interface not detected."
  ip -br link
  exit 1
fi

echo "Detected:  WAN=${WAN_IF}  LAN=${LAN_IF}"
echo

# ── 5. Netplan ───────────────────────────────────────────────────────────────
echo "==> [5/7] Writing netplan"
install -d /etc/netplan
cat > /etc/netplan/01-minifw.yaml <<EOF
# Generated by MiniFW setup USB
network:
  version: 2
  renderer: networkd

  ethernets:
    wan-usb:
      match:
        name: ${WAN_IF}
      dhcp4: true
      dhcp6: true
      optional: true

    lan-built-in:
      match:
        name: ${LAN_IF}
      addresses:
        - 192.168.10.1/24
      dhcp4: false
EOF

netplan apply
sleep 2

# ── 6. MiniFW config ─────────────────────────────────────────────────────────
echo "==> [6/7] Writing firewall config"
install -d /etc/minifw

if [[ ! -f /etc/minifw/firewall.yaml ]]; then
  cp "${USB_DIR}/config/firewall.example.yaml" /etc/minifw/firewall.yaml
fi

# Patch interface names in yaml (simple sed)
sed -i "s/^  wan:.*/  wan: ${WAN_IF}/" /etc/minifw/firewall.yaml
sed -i "s/^  lan:.*/  lan: ${LAN_IF}/" /etc/minifw/firewall.yaml

minifw apply
systemctl enable nftables dnsmasq
systemctl restart dnsmasq

# ── 7. Preflight ─────────────────────────────────────────────────────────────
echo "==> [7/7] Running preflight checks"
echo
set +e
bash "${USB_DIR}/preflight.sh"
PREFLIGHT=$?
set -e

echo
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Setup complete                                          ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo
echo "  WAN interface:  ${WAN_IF}"
echo "  LAN interface:  ${LAN_IF}"
echo "  Gateway:        192.168.10.1"
echo
echo "  Offline triage (always on this Mac Mini):"
echo "    cat /root/INTERNET-DOWN.txt"
echo "    ls /opt/minifw/docs/"
echo "    ls /opt/minifw/obsidian/"
echo
echo "  ── BEFORE CUTTING OVER FROM NETWORK BOX ──"
echo "  1. Plug Mac Mini LAN (${LAN_IF}) into your switch (or Network Box LAN for testing)"
echo "  2. Run:  sudo bash ${USB_DIR}/preflight.sh"
echo "  3. Read:  /opt/minifw/docs/SETUP-PLAN.md  (Phase 4 cutover)"
echo
echo "  ── IF INTERNET BREAKS ──"
echo "  cat /root/INTERNET-DOWN.txt"
echo "  sudo bash ${USB_DIR}/rollback-to-network-box.sh"
echo

if [[ "${PREFLIGHT}" -ne 0 ]]; then
  echo "  ⚠ Preflight had warnings — see above before cutover."
else
  echo "  ✓ Preflight passed (WAN may still need Fiber Jack connected)."
fi
