#!/usr/bin/env bash
# MiniFW one-shot setup — run from the USB stick on the Mac Mini.
#   cd /media/*/MINIFWSETUP && sudo ./setup.sh
#   sudo ./setup.sh --update    # refresh only (autorun uses this)
set -euo pipefail

UPDATE_MODE=0
if [[ "${1:-}" == "--update" ]]; then
  UPDATE_MODE=1
fi

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root: sudo $0"
  exit 1
fi

USB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ ! -f "${USB_DIR}/.minifw-usb" ]]; then
  if [[ "${MINIFW_USB_AUTORUN:-}" != "1" && "${MINIFW_NO_PROMPT:-}" != "1" ]]; then
    echo "Warning: this does not look like a MiniFW setup USB (.minifw-usb missing)."
    read -r -p "Continue anyway? [y/N] " ans
    [[ "${ans,,}" == "y" ]] || exit 1
  fi
fi

if [[ "${UPDATE_MODE}" -eq 1 ]]; then
  echo "╔══════════════════════════════════════════════════════════╗"
  echo "║  MiniFW USB — UPDATE / REPAIR mode                       ║"
  echo "╚══════════════════════════════════════════════════════════╝"
else
  echo "╔══════════════════════════════════════════════════════════╗"
  echo "║  MiniFW setup USB — Google Fiber + Mac Mini + Deco XE75  ║"
  echo "╚══════════════════════════════════════════════════════════╝"
fi
echo
echo "USB path: ${USB_DIR}"
echo

if [[ "${UPDATE_MODE}" -eq 1 ]]; then
  echo "==> Refreshing docs and minifw"
  install -d /opt/minifw/docs /opt/minifw/obsidian
  cp -f "${USB_DIR}/docs/"*.md /opt/minifw/docs/ 2>/dev/null || true
  cp -Rf "${USB_DIR}/obsidian/." /opt/minifw/obsidian/ 2>/dev/null || true
  cp -f "${USB_DIR}/EMERGENCY-CARD.txt" /root/INTERNET-DOWN.txt
  echo
  echo "==> [0/8] Checking internet route (1.1.1.1)..."
  if ! ip route get 1.1.1.1 >/dev/null 2>&1; then
    echo "No route to the internet from this Mac Mini yet."
    echo "Fix: ensure WAN link is up (use the USB Ethernet adapter as WAN if your built-in link isn't coming up)."
    echo "Then re-run:"
    echo "  cd /media/*/MINIFWSETUP && sudo ./setup.sh"
    exit 1
  fi

  apt-get update -qq
  python3 -m pip install --break-system-packages "${USB_DIR}/minifw" -q
  if [[ -f /etc/minifw/firewall.yaml ]]; then
    minifw apply
    systemctl restart dnsmasq
  fi
  bash "${USB_DIR}/install-usb-watcher.sh" 2>/dev/null || true
  bash "${USB_DIR}/preflight.sh" || true
  echo "==> Update complete"
  exit 0
fi

# ── 1. Packages ──────────────────────────────────────────────────────────────
echo
echo "==> [0/8] Checking internet route (1.1.1.1)..."
if ! ip route get 1.1.1.1 >/dev/null 2>&1; then
  echo "No route to the internet from this Mac Mini yet."
  echo "Fix: ensure WAN link is up (use the USB Ethernet adapter as WAN if your built-in link isn't coming up)."
  echo "Then re-run:"
  echo "  cd /media/*/MINIFWSETUP && sudo ./setup.sh"
  exit 1
fi

echo "==> [1/8] Installing system packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y nftables dnsmasq python3 python3-pip iproute2 curl

# ── 2. MiniFW ────────────────────────────────────────────────────────────────
echo "==> [2/8] Installing minifw from USB"
python3 -m pip install --break-system-packages "${USB_DIR}/minifw" -q

# ── 3. Offline docs on the Mac Mini (survives USB removal) ─────────────────
echo "==> [3/8] Installing offline docs to /opt/minifw"
install -d /opt/minifw/docs /opt/minifw/obsidian
cp -f "${USB_DIR}/docs/"*.md /opt/minifw/docs/ 2>/dev/null || true
cp -Rf "${USB_DIR}/obsidian/." /opt/minifw/obsidian/ 2>/dev/null || true
cp -f "${USB_DIR}/EMERGENCY-CARD.txt" /root/INTERNET-DOWN.txt
cp -f "${USB_DIR}/EMERGENCY-CARD.txt" /opt/minifw/EMERGENCY-CARD.txt
chmod 644 /opt/minifw/docs/* /root/INTERNET-DOWN.txt 2>/dev/null || true

# ── 4. Detect interfaces ─────────────────────────────────────────────────────
echo "==> [4/8] Detecting network interfaces"
echo
ip -br link
echo

WAN_IF=""
LAN_IF=""

# USB adapters: enx* or name contains usb
while IFS= read -r line; do
  name="${line%% *}"
  [[ "${name}" == "lo" ]] && continue
  [[ "${name}" == enx* ]] && WAN_IF="${name}" && continue
  [[ "${name}" == *usb* ]] && WAN_IF="${name}" && continue
done < <(ip -br link | awk '{print $1}')

# Built-in: first non-lo, non-wan, non-docker
while IFS= read -r line; do
  name="${line%% *}"
  [[ "${name}" == "lo" ]] && continue
  [[ "${name}" == "${WAN_IF}" ]] && continue
  [[ "${name}" == docker* ]] && continue
  [[ "${name}" == veth* ]] && continue
  [[ "${name}" == br-* ]] && continue
  LAN_IF="${name}"
  break
done < <(ip -br link | awk '{print $1}')

if [[ -z "${WAN_IF}" ]]; then
  echo "USB WAN adapter not detected. Plug in the USB Ethernet adapter and re-run."
  echo "Available interfaces:"
  ip -br link
  exit 1
fi

if [[ -z "${LAN_IF}" ]]; then
  echo "LAN interface not detected."
  ip -br link
  exit 1
fi

echo "Detected:  WAN=${WAN_IF}  LAN=${LAN_IF}"
echo

# ── 5. Netplan ───────────────────────────────────────────────────────────────
echo "==> [5/8] Writing netplan"
install -d /etc/netplan
cat > /etc/netplan/01-minifw.yaml <<EOF
# Generated by MiniFW setup USB
network:
  version: 2
  renderer: networkd

  ethernets:
    wan-usb:
      match:
        name: ${WAN_IF}
      dhcp4: true
      dhcp6: true
      optional: true

    lan-built-in:
      match:
        name: ${LAN_IF}
      addresses:
        - 192.168.10.1/24
      dhcp4: false
EOF

netplan apply
sleep 2

# ── 6. MiniFW config ─────────────────────────────────────────────────────────
echo "==> [6/8] Writing firewall config"
install -d /etc/minifw

if [[ ! -f /etc/minifw/firewall.yaml ]]; then
  cp "${USB_DIR}/config/firewall.example.yaml" /etc/minifw/firewall.yaml
fi

# Patch interface names in yaml (simple sed)
sed -i "s/^  wan:.*/  wan: ${WAN_IF}/" /etc/minifw/firewall.yaml
sed -i "s/^  lan:.*/  lan: ${LAN_IF}/" /etc/minifw/firewall.yaml

minifw apply
systemctl enable nftables dnsmasq
systemctl restart dnsmasq

# ── 7. Preflight ─────────────────────────────────────────────────────────────
echo "==> [7/8] Running preflight checks"
echo
set +e
bash "${USB_DIR}/preflight.sh"
PREFLIGHT=$?
set -e

echo
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Setup complete                                          ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo
echo "  WAN interface:  ${WAN_IF}"
echo "  LAN interface:  ${LAN_IF}"
echo "  Gateway:        192.168.10.1"
echo
echo "  Offline triage (always on this Mac Mini):"
echo "    cat /root/INTERNET-DOWN.txt"
echo "    ls /opt/minifw/docs/"
echo "    ls /opt/minifw/obsidian/"
echo
echo "  ── BEFORE CUTTING OVER FROM NETWORK BOX ──"
echo "  1. Plug Mac Mini LAN (${LAN_IF}) into your switch (or Network Box LAN for testing)"
echo "  2. Run:  sudo bash ${USB_DIR}/preflight.sh"
echo "  3. Read:  /opt/minifw/docs/SETUP-PLAN.md  (Phase 4 cutover)"
echo
echo "  ── IF INTERNET BREAKS ──"
echo "  cat /root/INTERNET-DOWN.txt"
echo "  sudo bash ${USB_DIR}/rollback-to-network-box.sh"
echo

if [[ "${PREFLIGHT}" -ne 0 ]]; then
  echo "  ⚠ Preflight had warnings — see above before cutover."
else
  echo "  ✓ Preflight passed (WAN may still need Fiber Jack connected)."
fi

# ── 8. Enable plug-and-play for future USB inserts ───────────────────────────
echo
echo "==> [8/8] Enabling plug-and-play USB watcher"
if [[ -f "${USB_DIR}/install-usb-watcher.sh" ]]; then
  bash "${USB_DIR}/install-usb-watcher.sh"
  echo "  ✓ Future MINIFWSETUP inserts will auto-run (update mode)"
else
  echo "  ⚠ install-usb-watcher.sh not found on USB — skip"
fi
