from __future__ import annotations

from pathlib import Path

from minifw.config import FirewallConfig

NFTABLES_PATH = Path("/etc/nftables.conf")
GENERATED_MARKER = "# Generated by minifw — do not edit below this line"


def render_nftables(config: FirewallConfig) -> str:
    wan = config.interfaces.wan
    lan = config.interfaces.lan
    lan_subnet = config.lan.subnet

    blocked_ips = "\n".join(
        f'        ip saddr {ip} drop' for ip in config.blocked_ips
    )
    allowed_wan = "\n".join(
        _render_allowed_wan_rule(wan, entry) for entry in config.allowed_wan_ports
    )
    port_forwards = "\n".join(
        _render_port_forward(wan, entry) for entry in config.port_forwards
    )

    icmp_rule = (
        "        icmp type echo-request accept"
        if config.allow_icmp
        else "        icmp type echo-request drop"
    )

    return f"""#!/usr/sbin/nft -f
# MiniFW nftables ruleset for {config.hostname}
flush ruleset

table inet filter {{
    chain input {{
        type filter hook input priority 0; policy drop;

        iif lo accept
        ct state established,related accept
        iif "{lan}" ip saddr {config.management_cidr} tcp dport {{ 22, 9090 }} accept
        iif "{lan}" ip saddr {config.management_cidr} udp dport 53 accept
        iif "{lan}" ip saddr {config.management_cidr} icmp type echo-request accept
        iif "{wan}" ct state invalid drop
{blocked_ips}
{icmp_rule}
    }}

    chain forward {{
        type filter hook forward priority 0; policy drop;

        ct state established,related accept
        iif "{lan}" oif "{wan}" ip saddr {lan_subnet} accept
        iif "{wan}" oif "{lan}" ct state established,related accept
{allowed_wan}
{port_forwards}
    }}

    chain output {{
        type filter hook output priority 0; policy accept;
    }}
}}

table ip nat {{
    chain prerouting {{
        type nat hook prerouting priority -100; policy accept;
{_render_prerouting(config)}
    }}

    chain postrouting {{
        type nat hook postrouting priority 100; policy accept;
        oif "{wan}" ip saddr {lan_subnet} masquerade
    }}
}}
"""


def _render_allowed_wan_rule(wan: str, entry: dict) -> str:
    proto = entry["proto"].lower()
    port = entry["port"]
    source = entry.get("source")
    if source:
        return f'        iif "{wan}" ip saddr {source} {proto} dport {port} accept'
    return f'        iif "{wan}" {proto} dport {port} accept'


def _render_port_forward(wan: str, entry) -> str:
    proto = entry.proto.lower()
    return (
        f'        iif "{wan}" {proto} dport {entry.wan_port} '
        f'ip daddr {entry.lan_ip} {proto} dport {entry.lan_port} accept'
    )


def _render_prerouting(config: FirewallConfig) -> str:
    wan = config.interfaces.wan
    lines = []
    for entry in config.port_forwards:
        proto = entry.proto.lower()
        lines.append(
            f'        iif "{wan}" {proto} dport {entry.wan_port} '
            f'dnat to {entry.lan_ip}:{entry.lan_port}'
        )
    return "\n".join(lines) if lines else "        # no port forwards configured"


def write_rules(config: FirewallConfig, path: Path = NFTABLES_PATH) -> None:
    content = render_nftables(config)
    path.write_text(content)
    path.chmod(0o644)
