#!/usr/bin/env python3
"""Sync AI Job Search assets from a source repo (preferably your fork).

This pulls:
- .claude/commands/** -> .claude/commands/ai-job-search/**
- .claude/skills/**   -> .claude/skills/ai-job-search/**
- .agents/skills/**   -> .agents/skills/ai-job-search/**

The source defaults to upstream but can be pointed to your fork via env vars:
- JOB_SEARCH_SKILL_SOURCE_REPO (e.g. peteedoo/ai-job-search)
- JOB_SEARCH_SKILL_SOURCE_REF  (e.g. master)
"""

from __future__ import annotations

import io
import json
import os
import shutil
import tarfile
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]

SOURCE_REPO = os.getenv("JOB_SEARCH_SKILL_SOURCE_REPO", "MadsLorentzen/ai-job-search").strip()
SOURCE_REF = os.getenv("JOB_SEARCH_SKILL_SOURCE_REF", "master").strip()
TOKEN = os.getenv("GH_STARS_TOKEN", "").strip() or os.getenv("GITHUB_TOKEN", "").strip()

TARGET_COMMANDS = ROOT / ".claude" / "commands" / "ai-job-search"
TARGET_CLAUDE_SKILLS = ROOT / ".claude" / "skills" / "ai-job-search"
TARGET_AGENT_SKILLS = ROOT / ".agents" / "skills" / "ai-job-search"
TARGET_META = ROOT / ".agents" / "state" / "ai-job-search-source.json"
TARGET_ATTR = ROOT / ".agents" / "skills" / "ai-job-search" / "ATTRIBUTIONS.generated.md"


def download_tarball(repo: str, ref: str) -> bytes:
    url = f"https://api.github.com/repos/{repo}/tarball/{ref}"
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "project-template-ai-job-search-sync",
    }
    if TOKEN:
        headers["Authorization"] = f"Bearer {TOKEN}"
    req = Request(url, headers=headers)
    with urlopen(req) as resp:
        return resp.read()


def ensure_clean_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def extract_tarball(blob: bytes, destination: Path) -> Path:
    ensure_clean_dir(destination)
    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as tf:
        tf.extractall(path=destination)
    children = [p for p in destination.iterdir() if p.is_dir()]
    if not children:
        raise RuntimeError("Downloaded archive did not contain a root directory.")
    return children[0]


def copy_tree_if_exists(source: Path, destination: Path) -> bool:
    if not source.exists() or not source.is_dir():
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, ignore=shutil.ignore_patterns(".git", ".git/*"))
    return True


def main() -> int:
    try:
        tarball = download_tarball(SOURCE_REPO, SOURCE_REF)
    except HTTPError as exc:
        raise SystemExit(f"Failed to download {SOURCE_REPO}@{SOURCE_REF}: {exc}") from exc

    scratch = ROOT / ".tmp" / "ai-job-search-sync"
    extracted_root = extract_tarball(tarball, scratch)

    copied = {
        "commands": copy_tree_if_exists(extracted_root / ".claude" / "commands", TARGET_COMMANDS),
        "claude_skills": copy_tree_if_exists(extracted_root / ".claude" / "skills", TARGET_CLAUDE_SKILLS),
        "agent_skills": copy_tree_if_exists(extracted_root / ".agents" / "skills", TARGET_AGENT_SKILLS),
    }

    TARGET_META.parent.mkdir(parents=True, exist_ok=True)
    TARGET_META.write_text(
        json.dumps(
            {
                "source_repo": SOURCE_REPO,
                "source_ref": SOURCE_REF,
                "synced_at": datetime.now(timezone.utc).isoformat(),
                "copied": copied,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    TARGET_ATTR.parent.mkdir(parents=True, exist_ok=True)
    TARGET_ATTR.write_text(
        "\n".join(
            [
                "# AI Job Search Source Attribution",
                "",
                "Generated by `scripts/sync_ai_job_search_fork.py`.",
                "",
                f"- Source repository: https://github.com/{SOURCE_REPO}",
                f"- Source ref: `{SOURCE_REF}`",
                "- License: MIT (from upstream repository metadata)",
                "",
                "Imported targets:",
                "- `.claude/commands/ai-job-search/`",
                "- `.claude/skills/ai-job-search/`",
                "- `.agents/skills/ai-job-search/`",
                "",
            ]
        ),
        encoding="utf-8",
    )

    if scratch.exists():
        shutil.rmtree(scratch)

    print(f"Synced AI Job Search assets from {SOURCE_REPO}@{SOURCE_REF}")
    print(f"Commands copied: {copied['commands']}")
    print(f"Claude skills copied: {copied['claude_skills']}")
    print(f"Agent skills copied: {copied['agent_skills']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
